### ISSUE TITLE
tardines-tracking

### ISSUE THREAD

**Issue by Etiram-Hasratov** [Etiram-Hasratov/Core-Banking#12]
- [ ] Gecikmə səbəblərini araşdırmaq , onların səbəblərini tapmaq
- [ ] Gecikmənin performansa təsirini araşdırmaq
- [ ] Ortalama gecikmə vaxtına görə müəyyən güzəştlərin tətbiqi
- [ ] İllərə görə gecikmə danmikasının ölçülməsi
- [ ] Maks gecikmə halların aşkar edilməsi (günlər üzrə)
- [ ] Son 1 il ərzində gecikmə sayını müəyyən etmək
- [ ] Son 1 ay ərzində gecikməyən işçilərin siyahısını əldə etmək
- [ ] Ortalama gecikmə müddəti ən az olan işçilərin maaşının artırılması və ya əlavə məzuniyyət günlərinin qazanılması
- [ ] Təyin edilmiş müddətdən çox davamlı gecikən işçilərlə maarifləndirici söhbət
- [ ] Gecikmələrin qarşısının alınması üçün görülən tədbirlər

- [ ] Tənbeh tədbirləri
- [ ] Tənbeh dərəcələri
- [ ] Həvəsləndirici tədbirlər

- [ ] 1-ci gecikmə xəbərdarlıq (hər gün 5 dəq artıq)
- [ ] 2-ci gecikmə izahat
- [ ] 3-cü gecikmə cərimə (əmək haqqının 1%-i)
